### ISSUE TITLE
google drive link doesn't seem to work

### ISSUE THREAD

**Issue by tomyoung903** [HLTCHKUST/adapterbot#3]
running the model downloading code gives an error:

Permission denied: https://drive.google.com/uc?id=1JQZex-AD-sa5WUT5U4lIn1K2sPW-us8a/
Maybe you need to change permission over 'Anyone with the link'?

**Comment by andreamad8** [comment]
Hi, 

maybe you can try to download it directly from https://drive.google.com/file/d/1JQZex-AD-sa5WUT5U4lIn1K2sPW-us8a/view?usp=sharing

Andrea
